channels:
- simpleitk
- conda-forge
- defaults
dependencies:
- imageio=2.2.0
- ipyparallel=6.0.2
- ipython=6.2.1
- ipywidgets=7.1.1
- jupyter=1.0.0
- keras=2.0.9
- matplotlib=2.1.2
- numpy=1.14.0
- pandas=0.22.0
- pillow=5.0.0
- python=3.6.4
- scipy=1.0.0
- tensorflow=1.0.0
- simpleitk=1.0.1
- tqdm=4.19.4
- pandas=0.22.0
- scikit-image=0.13.1
- opencv=3.3.1
- joblib=0.11
- scikit-learn=0.19.1
- h5py=2.7.1
- seaborn=0.8.1
- pandas_ml=0.5.0
- matplotlib-venn=0.11.5